grafana:
  enabled: true
  service:
    type: LoadBalancer
    loadBalancerIP: 10.13.13.15
  persistence:
    enabled: true
    type: sts
    storageClassName: "longhorn"
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection
  assertNoLeakedSecrets: false
  grafana.ini:
    auth:
      signout_redirect_url: "https://auth.salverdaserver.nl/application/o/grafana/end-session/"
      oauth_auto_login: true
    auth.generic_oauth:
      name: authentik
      enabled: true
      scopes: "openid profile email"
      auth_url: "https://auth.salverdaserver.nl/application/o/authorize/"
      token_url: "https://auth.salverdaserver.nl/application/o/token/"
      api_url: "https://auth.salverdaserver.nl/application/o/userinfo/"
      # Optionally map user groups to Grafana roles
      role_attribute_path: contains(groups, 'authentik Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'
    server:
      root_url: "https://grafana.salverdaserver.nl"

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: False
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    retention: 3d
    replicas: 1
    storageSpec: 
     volumeClaimTemplate:
       spec:
         storageClassName: longhorn
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 20Gi

prometheus-node-exporter:
  namespaceOverride: ""
  podLabels:
    ## Add the 'node-exporter' label to be used by serviceMonitor and podMonitor to match standard common usage in rules and grafana dashboards
    ##
    jobLabel: node-exporter
  releaseLabel: true
  extraArgs:
    - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|WDred|run/containerd/.+|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
    - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs|erofs)$
  service:
    portName: http-metrics
    ipDualStack:
      enabled: false
      ipFamilies: ["IPv6", "IPv4"]
      ipFamilyPolicy: "PreferDualStack"
    labels:
      jobLabel: node-exporter            

# Source - https://stackoverflow.com/a
# Posted by Sergei Kuzmin, modified by community. See post 'Timeline' for change history
# Retrieved 2025-12-10, License - CC BY-SA 4.0

prometheusOperator:
  namespaces: ''
  denyNamespaces: ''
  prometheusInstanceNamespaces: ''
  alertmanagerInstanceNamespaces: ''
  thanosRulerInstanceNamespaces: ''

