apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: longhorn-vlan
  namespace: longhorn-system
spec:
  config: '{
            "cniVersion": "0.3.0",
            "type": "macvlan",
            "master": "longhorn",
            "vlan": 500,
            "mode": "bridge",
            "ipam": {
                "type": "dhcp"
            }
        }'
