repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: metallb
  url: https://metallb.github.io/metallb
- name: longhorn
  url: https://charts.longhorn.io
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: jetstack
  url: https://charts.jetstack.io
- name: wg-easy
  url: https://helm-charts.rm3l.org
- name: goauthentik
  url: https://charts.goauthentik.io/
- name: postgreSQL
  url: registry-1.docker.io/bitnamicharts
  oci: true
- name: pgadmin
  url: https://helm.runix.net
- name: immich
  url: ghcr.io/immich-app/immich-charts
  oci: true
- name: ddns
  url: https://cloudflare-ddns.aureum.cloud
- name: multus
  url: https://rke2-charts.rancher.io
- name: openwebui
  url: https://open-webui.github.io/helm-charts
- name: searxng
  url: https://charts.kubito.dev
- name: miniflux
  url: https://charts.gabe565.com
- name: planka
  url: http://plankanban.github.io/planka
- name: bitwarden
  url: https://gissilabs.github.io/charts

releases:
  # load balancer
- name: metallb
  namespace: metallb-system
  chart: metallb/metallb

  # ingress
- name: nginx-ingress
  namespace: nginx-system
  chart: ingress-nginx/ingress-nginx
  set:
    - name: controller.replicaCount
      value: 2 
    - name: controller.service.loadBalancerIP
      value: 10.13.13.10
    - name: controller.enableSnippets
      value: true
    - name: controller.allowSnippetAnnotations
      value: true
    - name: controller.config.annotations-risk-level
      value: critical
    - name: controller.config.use-forwarded-headers
      value: true
    - name: controller.config.real_ip_header
      value: CF-Connecting-IP

  # certmanager
- name: cert-manager
  namespace: nginx-system
  chart: jetstack/cert-manager
  set:
    - name: crds.enabled
      value: true

#   #Storage
- name: longhorn
  namespace: longhorn-system
  chart: longhorn/longhorn
  version: 1.9.1
  values:
    - ./values/longhorn.values.yaml

   # monitoring
- name: kube-prometheus-stack
  namespace: monitoring
  chart: prometheus-community/kube-prometheus-stack
  version: 73.0.0
  values:
    - ./values/grafana.values.yaml
  secrets:
    - ./secrets/grafana.yaml

- name: openwebui
  namespace: applications
  chart: openwebui/open-webui
  version: 8.14.0
  values: 
    - ./values/webui.values.yaml
  secrets:
    - ./secrets/webui.yaml

    #vpn
# - name: wg-easy
#   namespace: vpn
#   chart: wg-easy/wg-easy
#   version: 0.2.0
#   values:
#     - ./values/wg-easy.values.yaml

- name: authentik
  namespace: auth
  chart: goauthentik/authentik
  version: 2025.8.4
  values:
    - ./values/auth.values.yaml
  secrets:
    - ./secrets/auth.yaml

- name: postgres
  namespace: database
  chart: postgreSQL/postgresql
  version: 16.7.20
  values:
    - ./values/postgres.values.yaml
  secrets:
    - ./secrets/postgress.yaml

- name: pgadmin
  namespace: database
  chart: pgadmin/pgadmin4
  version: 1.47.0
  values:
    - ./values/pgadmin.values.yaml
  secrets:
    - ./secrets/pgadmin.yaml

- name: immich
  namespace: applications
  chart: immich/immich
  version: 0.9.2
  values:
    - ./values/immich.values.yaml
  secrets:
    - ./secrets/immich.yaml

- name: ddns
  namespace: applications
  chart: ddns/cloudflare-ddns
  version: 1.0.3
  secrets:
    - ./secrets/ddns.yaml

# - name: nextcloud
#   namespace: applications
#   chart: nextcloud/nextcloud
#   version: 7.0.0
#   values:
#     - ./values/nextcloud.values.yaml
#   secrets:
#     - ./secrets/cloud.yaml
- name: miniflux
  namespace: applications
  chart: miniflux/miniflux
  version: 0.9.2
  values:
    - ./values/miniflux.values.yaml
  secrets:
    - ./secrets/miniflux.yaml

- name: planka
  namespace: applications
  chart: planka/planka
  version: 1.0.5
  values:
    - ./values/planka.values.yaml
  secrets:
    - ./secrets/planka.yaml

- name: multus
  namespace: kube-system
  chart: multus/rke2-multus
  values:
    - ./values/multus.values.yaml

- name: vaultwarden
  namespace: applications
  chart: bitwarden/vaultwarden
  version: 1.2.6
  values:
    - ./values/vault.values.yaml
  secrets:
    - ./secrets/vault.yaml

- name: searxng
  namespace: applications
  chart: searxng/searxng
  values:
    - ./values/searxng.values.yaml
