repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: metallb
  url: https://metallb.github.io/metallb
- name: longhorn
  url: https://charts.longhorn.io
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
  # load balancer
- name: metallb
  namespace: metallb-system
  chart: metallb/metallb

- name: nginx-ingress
  namespace: nginx-system
  chart: ingress-nginx/ingress-nginx
  set:
    - name: controller.replicaCount
      value: 2

#   #Storage
- name: longhorn
  namespace: longhorn-system
  chart: longhorn/longhorn
  values:
    - ./values/longhorn.values.yaml

   # monitoring
- name: kube-prometheus-stack
  namespace: monitoring
  chart: prometheus-community/kube-prometheus-stack
  set:
    - name: grafana.service.type
      value: "LoadBalancer"
    - name: grafana.service.loadBalancerIP
      value: 10.13.13.15
    - name: grafana.ingress.enabled
      value: true
    - name: grafana.ingress.hosts
      values: 
        - grafana.salverdaserver.nl
    - name: grafana.ingress.ingressClassName
      value: nginx

