repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: metallb
  url: https://metallb.github.io/metallb
- name: longhorn
  url: https://charts.longhorn.io
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: jetstack
  url: https://charts.jetstack.io
- name: wg-easy
  url: https://helm-charts.rm3l.org
- name: external-dns
  url:  https://kubernetes-sigs.github.io/external-dns/

releases:
  # load balancer
- name: metallb
  namespace: metallb-system
  chart: metallb/metallb

  # ingress
- name: nginx-ingress
  namespace: nginx-system
  chart: ingress-nginx/ingress-nginx
  set:
    - name: controller.replicaCount
      value: 2 
    - name: controller.service.loadBalancerIP
      value: 10.13.13.10

- name: external-dns
  namespace: nginx-system
  chart: external-dns/external-dns
  values:
    - ./values/dns.values.yaml

  # certmanager
- name: cert-manager
  namespace: nginx-system
  chart: jetstack/cert-manager
  set:
    - name: crds.enabled
      value: true

#   #Storage
- name: longhorn
  namespace: longhorn-system
  chart: longhorn/longhorn
  values:
    - ./values/longhorn.values.yaml

   # monitoring
- name: kube-prometheus-stack
  namespace: monitoring
  chart: prometheus-community/kube-prometheus-stack
  version: 73.0.0
  values:
    - ./values/grafana.values.yaml

- name: loki-grafana
  namespace: monitoring
  chart: grafana/loki
  values:
    - ./values/loki.values.yaml

    #vpn
- name: wg-easy
  namespace: vpn
  chart: wg-easy/wg-easy
  version: 0.2.0
  values:
    - ./values/wg-easy.values.yaml
